# Generated by Django 5.1.6 on 2025-03-06 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(default='Full-time', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
