# Generated by Django 5.1.6 on 2025-03-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application_cover_letter_application_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('Remote', 'Remote - Work from anywhere'), ('On-site: New York, NY, USA', 'On-site: New York, NY, USA'), ('On-site: San Francisco, CA, USA', 'On-site: San Francisco, CA, USA'), ('On-site: Austin, TX, USA', 'On-site: Austin, TX, USA'), ('On-site: Chicago, IL, USA', 'On-site: Chicago, IL, USA'), ('Hybrid: San Francisco, CA, USA', 'Hybrid: San Francisco, CA, USA'), ('Hybrid: New York, NY, USA', 'Hybrid: New York, NY, USA'), ('On-site: Kigali, Rwanda', 'On-site: Kigali, Rwanda'), ('On-site: Nairobi, Kenya', 'On-site: Nairobi, Kenya'), ('On-site: Lagos, Nigeria', 'On-site: Lagos, Nigeria'), ('On-site: Accra, Ghana', 'On-site: Accra, Ghana'), ('Hybrid: Kigali, Rwanda', 'Hybrid: Kigali, Rwanda'), ('Hybrid: Nairobi, Kenya', 'Hybrid: Nairobi, Kenya')], default='Remote', max_length=100),
        ),
    ]
