# Generated by Django 5.1.6 on 2025-03-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.AddField(
            model_name='job',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
